Repository arjunptm/GITS, pull requests merged in 2021-09, with the labels that each got.

#27 OI26 : Fixed Path Errors in Test Files
  code/gits_add.py
  code/gits_all_branch.py
  test/test_checkout.py
  test/test_gits_add.py
  test/test_gits_all_branch.py
  test/test_gits_commit.py
  test/test_gits_create_branch.py
Labels: bug

#25 OI21: Added clone functionality
  README.md
  code/gits.py
  code/gits_clone.py
  test/test_gits_clone.py
Labels: enhancement

#19 Added the mv functionality
  README.md
  code/gits.py
  code/gits_mv.py
Labels: enhancement

#35 Fixed the python3/python instruction and started sales pitch section
  README.md
Labels: documentation

#22 Gits pull #11
  README.md
  code/gits_pull.py
Labels: enhancement
